### ISSUE TITLE
Installation sous Linux Ubuntu >= 14.04

### ISSUE THREAD

**Issue by lluc** [e-dot/bcdlibre#1]
L'installation, telle que décrite dans le fichier _Markdown_ ne semble pas fonctionner.
Est-elle à jour ou faut-il prévoir des dispositions spécifiques pour une distribution (Linux) donnée ?

**Comment by lluc** [comment]
Oups ! Erreur de ma part ...
=> je faisait référence au _readme.md_ et non au _install.md_

**Comment by lluc** [comment]
Cependant, après avoir lancé la commande : 
`bash setup/setup.sh
`
, j'ai au final l'erreur suivante : 
`[2017-01-19 18:23:29] ERROR: Can't install nodejs!`

**Comment by lluc** [comment]
Après un premier débogage, il s'avérerait que le message d'erreur vient de cette ligne : 
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - || handle_error "Can't install nodejs!"`

**Comment by lluc** [comment]
Problème résolu !  :-)
=> cela était dû à des paquets non trouvés. Ces éléments n'ayant par ailleurs rien à voir avec l'installation de _BDC Libre_.

**Comment by e-dot** [comment]
Bonsoir,

Tant mieux si l'installation est finalement OK - pouvez-vous préciser de quelle distribution de Linux il s'agit et quels paquets étaient manquants afin que les prochains puissent en profiter?

Merci,

E.

**Comment by lluc** [comment]
Il s'agit d'une XUbuntu 14.04.
Par contre, le module à l'origine de l'erreur n'a rien à voir avec _BCD Libre_ puisqu'il s'agissait d'un ancien dépôt de Tox, qui ne pouvait plus être joint.
Une fois ce dernier supprimé du _sources.list_, tout est rentré dans l'ordre. :-)

**Comment by e-dot** [comment]
Ok merci - je ferme ce bug, s'il y a d'autres problèmes avec Ubuntu n'hésitez pas à me les signaler.

Sinon, je mettrais volontiers "compatible avec Ubuntu 14.04" dans le readme!

E.
